[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault_q4_25 = "FQZTszJjBr5jWzb3bQpAvspjF9YH6fPBqGFS2kYQ69HF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/haze/backpack.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
